services:

  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092" # for client connections
      - "9101:9101" # JMX
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      - kafka
    command: "bash -c \
                'kafka-topics --create --topic stats.events-similarity.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092 && \
                kafka-topics --create --topic stats.user-actions.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092'"
    init: true

  analyzer-db:
    image: postgres:16.1
    container_name: ewm-stats-analyzer-db-container
    ports:
      - "5424:5432"
    environment:
      - POSTGRES_DB=ewm-stats-analyzer
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    volumes:
      - ewm_stats_analyzer_data:/var/lib/postgresql/data
    restart: on-failure

  comments-db:
    image: postgres:16.1
    container_name: ewm-core-comments-db-container
    ports:
      - "5425:5432"
    environment:
      - POSTGRES_DB=ewm-core-comments
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    volumes:
      - ewm_core_comments_data:/var/lib/postgresql/data
    restart: on-failure

  events-db:
    image: postgres:16.1
    container_name: ewm-core-events-db-container
    ports:
      - "5427:5432"
    environment:
      - POSTGRES_DB=ewm-core-events
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    volumes:
      - ewm_core_events_data:/var/lib/postgresql/data
    restart: on-failure

  requests-db:
    image: postgres:16.1
    container_name: ewm-core-requests-db-container
    ports:
      - "5428:5432"
    environment:
      - POSTGRES_DB=ewm-core-requests
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    volumes:
      - ewm_core_requests_data:/var/lib/postgresql/data
    restart: on-failure

  users-db:
    image: postgres:16.1
    container_name: ewm-core-users-db-container
    ports:
      - "5429:5432"
    environment:
      - POSTGRES_DB=ewm-core-users
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    volumes:
      - ewm_core_users_data:/var/lib/postgresql/data
    restart: on-failure

  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-service-db-container
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    volumes:
      - ewm_stats_data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  ewm_stats_analyzer_data:
  ewm_stats_data:
  ewm_core_comments_data:
  ewm_core_events_data:
  ewm_core_requests_data:
  ewm_core_users_data: