logging:
  level:
    root: INFO

grpc:
  server:
    port: 0

aggregator:
  kafka:
    common-properties:
      "bootstrap.servers": localhost:9092
      "enable.auto.commit": false
    consumers:
      - type: UserActionsProcessor
        properties:
          "key.deserializer": "org.apache.kafka.common.serialization.LongDeserializer"
          "value.deserializer": "ru.practicum.kafka.deserializer.UserActionDeserializer"
          "group.id": "stats.aggregator.user-actions"
        topics:
          - "stats.user-actions.v1"
        poll-timeout: 500ms
    producers:
      - type: EventSimilarityProcessor
        properties:
          "key.serializer": "org.apache.kafka.common.serialization.LongSerializer"
          "value.serializer": "ru.practicum.kafka.serializer.UserActionSerializer"
        topics:
          - "stats.events-similarity.v1"